package model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;

import java.sql.Date;
import java.util.List;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import util.PurchasedItems;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Getter
@Setter
@DynamoDBTable(tableName = "purchase_receipts")
public class Order {
    @DynamoDBAttribute
    private List<PurchasedItems> items;
    @DynamoDBRangeKey
    @DynamoDBAttribute(attributeName = "customer_id")
    private Integer customerId;
    @DynamoDBAttribute(attributeName = "store_id")
    private Integer storeId;
    @DynamoDBTypeConverted(converter = InstantDateConverter.class)
    private Date date;
    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey
    private String id;
}
